# Numpy

fundamental package for sci computing w/ Python

## Arrays

* v[j]
* ndim = 1
* shape = (N,)

* A[j,k]
* ndim = 2
* shape = (N,M)

## Datatypes

* Ints
    * numpy.int8
    * numpy.int16
    * numpy.int32
    * numpy.int64
    * numpy.uint32
* float
    * numpy.float32
    * numpy.float64
    * numpy.float128
    * numpy.complex64
* dtypes
    * bool
    * void
    * object (refer to any type of python object)
    
## Learning Objectives

1. Creating arrays: from a list, empty, zero, random, and linear spaced
2. Interrogating the dtype and shape of arrays
3. Composing Arrays
4. Loading and saving arrays

In [1]:
import numpy as np
import matplotlib.pyplot as pp

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
a.dtype

dtype('int64')

In [5]:
a = np.array([1,2,3,4,5], dtype=np.float64)

In [6]:
a

array([1., 2., 3., 4., 5.])

In [7]:
a.ndim, a.shape, a.size

(1, (5,), 5)

In [9]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]], dtype=np.float64)

In [10]:
b

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [11]:
b.ndim, b.shape, b.size

(2, (2, 5), 10)

In [12]:
np.zeros((3,3), 'd')

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.empty((4,4), 'd')

array([[ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         9.28548869e+242],
       [-2.00000000e+000, -2.00000000e+000,  9.38724727e-323,
         0.00000000e+000]])

In [14]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [16]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [17]:
np.random.standard_normal((2,4))

array([[-0.83818036,  1.65810975, -1.38678464, -1.24793236],
       [-1.10082478, -1.53392842, -1.12715285,  1.15680628]])

In [18]:
a = np.random.standard_normal((2,3))
b = np.random.standard_normal((2,3))

In [19]:
np.vstack([a,b])

array([[-1.0722756 , -0.43308256,  0.85278198],
       [-0.73772814,  0.2131038 ,  0.83015933],
       [ 0.05015379, -0.08774248, -0.09801955],
       [-0.00875576,  0.68911482, -1.39866966]])

In [20]:
np.hstack([a,b])

array([[-1.0722756 , -0.43308256,  0.85278198,  0.05015379, -0.08774248,
        -0.09801955],
       [-0.73772814,  0.2131038 ,  0.83015933, -0.00875576,  0.68911482,
        -1.39866966]])

In [21]:
a.transpose()

array([[-1.0722756 , -0.73772814],
       [-0.43308256,  0.2131038 ],
       [ 0.85278198,  0.83015933]])

In [22]:
b.transpose()

array([[ 0.05015379, -0.00875576],
       [-0.08774248,  0.68911482],
       [-0.09801955, -1.39866966]])

In [23]:
np.save('example.npy',a)

In [24]:
al = np.load('example.npy')

In [25]:
al

array([[-1.0722756 , -0.43308256,  0.85278198],
       [-0.73772814,  0.2131038 ,  0.83015933]])

In [26]:
a

array([[-1.0722756 , -0.43308256,  0.85278198],
       [-0.73772814,  0.2131038 ,  0.83015933]])

In [27]:
a == al

array([[ True,  True,  True],
       [ True,  True,  True]])