# Numpy

fundamental package for sci computing w/ Python

## Arrays

* v[j]
* ndim = 1
* shape = (N,)

* A[j,k]
* ndim = 2
* shape = (N,M)

## Datatypes

* Ints
    * numpy.int8
    * numpy.int16
    * numpy.int32
    * numpy.int64
    * numpy.uint32
* float
    * numpy.float32
    * numpy.float64
    * numpy.float128
    * numpy.complex64
* dtypes
    * bool
    * void
    * object (refer to any type of python object)
    
## Learning Objectives

1. Creating arrays: from a list, empty, zero, random, and linear spaced
2. Interrogating the dtype and shape of arrays
3. Composing Arrays
4. Loading and saving arrays

In [1]:
import numpy as np
import matplotlib.pyplot as pp

In [2]:
a = np.array([1,2,3,4,5])

In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
a.dtype

dtype('int64')

In [5]:
a = np.array([1,2,3,4,5], dtype=np.float64)

In [6]:
a

array([1., 2., 3., 4., 5.])

In [7]:
a.ndim, a.shape, a.size

(1, (5,), 5)

In [9]:
b = np.array([[1,2,3,4,5],[6,7,8,9,10]], dtype=np.float64)

In [10]:
b

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [11]:
b.ndim, b.shape, b.size

(2, (2, 5), 10)

In [12]:
np.zeros((3,3), 'd')

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.empty((4,4), 'd')

array([[ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000],
       [ 0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         9.28548869e+242],
       [-2.00000000e+000, -2.00000000e+000,  9.38724727e-323,
         0.00000000e+000]])

In [ ]:
np.linespace